language: c

os: linux

compiler:
    - clang
    - gcc

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libpcap-dev libnet-dev

script:
    - sh autogen.sh
    - sh configure
    - make

after_success:
    - bash <(curl -s https://codecov.io/bash)
