name: arptools

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  main:
    name: ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: deps
        run: |
          sudo apt update
          sudo apt install libpcap-dev libnet-dev
      - name: autogen
        run: sh autogen.sh
      - name: configure
        run: ./configure
      - name: make
        run: make -j
